### ISSUE TITLE
[META] Ideas 💡

### ISSUE THREAD

**Issue by moul** [pmg-tools/berty-bot-experiments#2]
* Gomod Flow Examples
  * [x] 1-bot-official-go-dep (#1)
  * [x] 2-bot-fork-go-dep (#3)
  * [x] 3-bot-rel-clone-go-dep (#4)
  * [x] 4-bot-custom-sdk (#5)
* [ ] Set up CI
* [ ] Share feedback of DX improvement ideas w/ Berty core team
  * should have a standalone bertybot SDK with minimal deps
  * should have a way to mock for testing/dev
  * should have a no-brainer way to embed a full berty node (not default)
